# ---
# # Jaeger MySQL Storage Plugin Deployment
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: jaeger-mysql-plugin
#   namespace: tracing
#   labels:
#     app: jaeger-mysql-plugin
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: jaeger-mysql-plugin
#   template:
#     metadata:
#       labels:
#         app: jaeger-mysql-plugin
#     spec:
#       containers:
#       - name: plugin
#         image: alpine:latest
#         command:
#         - /bin/sh
#         - -c
#         - |
#           # 设置文件描述符限制，避免 "too many open files" 错误
#           ulimit -n 65536
#           exec /app/jaeger-mysql-plugin \
#             --grpc-addr=:17271 \
#             --mysql-addr=manticore:9306 \
#             --mysql-db= \
#             --mysql-user=root \
#             --mysql-pass=
#         ports:
#         - containerPort: 17271
#           name: grpc
#           protocol: TCP
#         volumeMounts:
#         - name: binary
#           mountPath: /app
#           readOnly: true
#         resources:
#           requests:
#             memory: "128Mi"
#             cpu: "100m"
#           limits:
#             memory: "512Mi"
#             cpu: "500m"
#         securityContext:
#           # 允许设置更高的资源限制
#           runAsNonRoot: false
#           runAsUser: 0
#           capabilities:
#             add:
#             - SYS_RESOURCE
#         livenessProbe:
#           tcpSocket:
#             port: 17271
#           initialDelaySeconds: 10
#           periodSeconds: 10
#         readinessProbe:
#           tcpSocket:
#             port: 17271
#           initialDelaySeconds: 5
#           periodSeconds: 5
#       volumes:
#       - name: binary
#         hostPath:
#           path: /Users/tal/dock/goutils/k3s/lianlu/jaeger-mysql-plugin
#           type: Directory

# ---
# # Service for MySQL Storage Plugin
# apiVersion: v1
# kind: Service
# metadata:
#   name: jaeger-mysql-plugin
#   namespace: tracing
#   labels:
#     app: jaeger-mysql-plugin
# spec:
#   type: ClusterIP
#   # 对于 gRPC，设置 sessionAffinity: None 以确保多副本负载均衡
#   # gRPC 使用 HTTP/2 长连接，默认会保持会话亲和性，可能导致流量只到一个 pod
#   # 注意：由于 gRPC 的长连接特性，即使设置了 sessionAffinity: None，
#   # 已建立的连接仍会保持到同一个 pod。新连接会按负载均衡策略分发。
#   # 如果需要更好的负载均衡，可以考虑：
#   # 1. 增加副本数（replicas）
#   # 2. 使用 Headless Service + gRPC 客户端负载均衡（需要客户端支持）
#   sessionAffinity: None
#   ports:
#   - port: 17271
#     targetPort: 17271
#     protocol: TCP
#     name: grpc
#   selector:
#     app: jaeger-mysql-plugin

---
# Jaeger Collector with gRPC Storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-collector
  namespace: tracing
  labels:
    app: jaeger
    component: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
      component: collector
  template:
    metadata:
      labels:
        app: jaeger
        component: collector
    spec:
      containers:
      - name: jaeger-collector
        image: quay.io/jaegertracing/jaeger-collector:latest
        imagePullPolicy: IfNotPresent
        args:
        - --grpc-storage.server=jaeger-mysql-plugin:17271
        - --grpc-storage.tls.enabled=false
        env:
        - name: SPAN_STORAGE_TYPE
          value: grpc
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        ports:
        - containerPort: 14250
          name: grpc
          protocol: TCP
        - containerPort: 14268
          name: http
          protocol: TCP
        - containerPort: 14269
          name: admin
          protocol: TCP
        - containerPort: 4317
          name: otlp-grpc
          protocol: TCP
        - containerPort: 4318
          name: otlp-http
          protocol: TCP
        - containerPort: 9411
          name: zipkin
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 10
          periodSeconds: 10

---
# Jaeger Query with gRPC Storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query
  namespace: tracing
  labels:
    app: jaeger
    component: query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
      component: query
  template:
    metadata:
      labels:
        app: jaeger
        component: query
    spec:
      containers:
      - name: jaeger-query
        image: quay.io/jaegertracing/jaeger-query:latest
        imagePullPolicy: IfNotPresent
        args:
        - --grpc-storage.server=jaeger-mysql-plugin:17271
        - --grpc-storage.tls.enabled=false
        env:
        - name: SPAN_STORAGE_TYPE
          value: grpc
        ports:
        - containerPort: 16686
          name: query-http
          protocol: TCP
        - containerPort: 16687
          name: admin
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 16687
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 16687
          initialDelaySeconds: 10
          periodSeconds: 10

---
# Service for Jaeger Collector
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: tracing
  labels:
    app: jaeger
    component: collector
spec:
  type: NodePort
  ports:
  - port: 14250
    targetPort: 14250
    nodePort: 30250
    protocol: TCP
    name: grpc
  - port: 14268
    targetPort: 14268
    nodePort: 30268
    protocol: TCP
    name: http
  - port: 9411
    targetPort: 9411
    nodePort: 30411
    protocol: TCP
    name: zipkin
  - port: 4317
    targetPort: 4317
    nodePort: 30317
    protocol: TCP
    name: otlp-grpc
  - port: 4318
    targetPort: 4318
    nodePort: 30318
    protocol: TCP
    name: otlp-http
  - port: 14269
    targetPort: 14269
    protocol: TCP
    name: admin
  selector:
    app: jaeger
    component: collector

---
# Service for Jaeger Query
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: tracing
  labels:
    app: jaeger
    component: query
spec:
  type: NodePort
  ports:
  - port: 16686
    targetPort: 16686
    nodePort: 30686
    protocol: TCP
    name: ui
  - port: 16685
    targetPort: 16685
    nodePort: 32503
    protocol: TCP
    name: grpc
  selector:
    app: jaeger
    component: query

---
# Headless Service for Jaeger Agent
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: tracing
  labels:
    app: jaeger
    component: agent
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5775
    targetPort: 5775
    protocol: UDP
    name: compact
  - port: 6831
    targetPort: 6831
    protocol: UDP
    name: binary
  - port: 6832
    targetPort: 6832
    protocol: UDP
    name: compact-binary
  - port: 5778
    targetPort: 5778
    protocol: TCP
    name: configs
  selector:
    app: jaeger
    component: agent

---
# DaemonSet for Jaeger Agent
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jaeger-agent
  namespace: tracing
  labels:
    app: jaeger
    component: agent
spec:
  selector:
    matchLabels:
      app: jaeger
      component: agent
  template:
    metadata:
      labels:
        app: jaeger
        component: agent
    spec:
      containers:
      - name: jaeger-agent
        image: quay.io/jaegertracing/jaeger-agent:latest
        imagePullPolicy: IfNotPresent
        args:
        - --reporter.grpc.host-port=jaeger-collector:14250
        ports:
        - containerPort: 5775
          protocol: UDP
          name: compact
        - containerPort: 6831
          protocol: UDP
          name: binary
        - containerPort: 6832
          protocol: UDP
          name: compact-bin
        - containerPort: 5778
          protocol: TCP
          name: configs
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
