apiVersion: v1
kind: ServiceAccount
metadata:
  name: kite
  namespace: kube-system
---
# 演示/开发：直接给 Kite cluster-admin，省去逐条补 RBAC。
# 生产环境请改成最小权限（按需放开 resources/verbs）。
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kite-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kite
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kite
  namespace: kube-system
  labels:
    app: kite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kite
  template:
    metadata:
      labels:
        app: kite
    spec:
      serviceAccountName: kite
      containers:
        - name: kite
          image: ghcr.io/zxh326/kite:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kite
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: kite
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      # 避免和仓库里 Jaeger UI(30686) / Dashboard(30080) 冲突
      nodePort: 30081

